For the next three questions, you must create a new notebook on your computer and paste the code of the questions on separate cells. 
Then, you must implement the code according de docstrings. PLEASE, READ THEM CAREFULLY.
You have to paste the following code and run it on the first cell to been able to execute the functions.

# Begin of the code
import pandas as pd
import numpy as np

df = pd.DataFrame(columns=list("ABCDEFGHIJ"),data=[[ 33,  29, 101,   3,  69, 128,  65,  50,  52, 146], [135,  74,  97,  45,  33,  58,  99,  92,  35, 119], [ 45,  77, 119,  64,  22, 119,  42, 146,  96,  95], [ 63,  37,   1,  47,  73,  35,  75,  51,  18,  82], [ 90,  33,  58,  62,  92,  55,  40,  27,  42,  25], [107,  37,  73, 130,  45,  52,  40, 124,  77,  65], [137, 110, 130, 123,  97,  88, 101, 149,  81,   4], [ 75,  76, 111, 118,  35,  36,  72,  87,  19,  32], [ 88,  31,  83,  23, 103,  35,  23,  43, 144,   8], [102,   6, 106, 144, 102,  80,  50, 139, 104,  66], [ 34,  62, 138, 139, 112,   8, 104, 122,  91, 115], [ 60,  61,   4,  73,  63,  16, 140, 104,  53,  77], [ 66, 128,  82, 130,  11,  90, 122, 145,  55,  98], [ 86, 142,  62,  20,  31,  15, 107, 136,   4, 117], [ 13,  43,  52,  49,  87, 137,  40, 145,  27, 140], [131,  77,  77, 133, 131, 118,  56, 122, 120,  57], [140, 115,  32, 140,  90, 121,  24, 133, 138, 118], [ 10, 138, 130, 113,  87,  63,  22,  25, 128,  92], [ 15,  37,  55,  74, 125,  42,  20,  58, 133, 109], [116,  86,  94,  18,  70,  39, 148,  75, 120, 127], [ 71,  66,  34,  86,  43, 143,  31,  66, 101, 136], [119, 121,  29,  52,  47,  87,  18,  23,  75,  36], [106, 142,   6,  17, 131,  81,   1, 120,  43,  34], [106,  11,  51, 114,  62, 104,  60,  45, 114,   4], [ 80, 110, 102,  14, 114, 123, 145,  51, 122, 118], [143, 124, 145,  19, 140,  67,  70,  88,  61,  95], [148, 124,  64,  76,  44,  75,  23,  33,  14,  52], [103, 102, 108,  30,  34, 144,  82, 126,  71, 117], [ 65,  91, 134,  86,  72,  21, 140,  50,  11,  29], [ 61,  75, 116, 103,  43,  24,  11,  46,  24,  64], [107, 111,  19,   2,  60,  98,  90,  78, 149, 113], [ 69,  18, 146,  98, 132,  58,  76,  45,   3,  31], [ 72,   4, 128,  52,  91,  85,   8, 120,  63,  34], [104, 119, 144, 102, 115,  28,  10, 103, 104,  51], [ 66,  36,  75,   9, 138, 110,  92, 119, 116,  76], [128, 144, 124,  43, 126, 103,  97,   7,  25, 126], [ 36,   3, 145, 107,  28, 146,  88,  54, 107,  10], [ 74,  89, 106, 127, 119,  90,  74, 149,   8,   5], [ 83,  18,  18,  84,  20,  60, 115, 106,  66, 128], [ 90,  18,  19, 117,  68,  33,  70,  41,  83,  42], [108, 109,  55,  15,  43,   7,  34,  65, 118, 144], [ 28, 123,  24, 148,  81, 142, 113, 112,  36, 138], [ 52, 108,  35,   5, 125,  82,  10,  27,  64,  67], [139, 149,  76,  35,  72,  83,  54,  72,  97, 123], [ 37,  22, 143, 105, 147,  61, 140,  27, 141, 117], [148, 126, 118,  32,  99, 139, 101, 136,  50,  86], [142, 131,  58, 105,  61, 128,  38, 142, 121,  11], [141, 127,  46, 141, 132,  66,   7, 113, 116, 105], [ 20,  18,  89,  60,  58,  37,  86,  67, 109, 117], [ 47,  45, 120, 136, 124,  51,  69,  49,  62, 115], [124, 138,  93,  28,  95,  82, 115,  97,  28,  81], [ 36, 108,  50,  17, 105, 125, 105,  65,  50,  42], [118,  53, 100, 129,  73, 132, 148,  61,  66,  54], [ 40, 120,  51, 143,  88, 128,   4,  93,  79,  97], [ 48,  97, 133, 124, 132,  98,   8,  36,  38,  71], [ 33, 108,  61,  33,  12, 132,  37, 102, 141,  27], [ 31,  69, 139,   3,  21,  40, 124,  47,  86, 143], [ 66,  38, 100,   9,  67,  45,  20,  62, 130,  65], [  5,  31,  85,  16,  40, 132, 147,  92,  18, 123], [ 88,  51, 129,  68,  18,  81,  15, 118,  50,  92], [140,  49, 122, 134,  94,  58, 138,  71,  25,  96], [134,  93,  17, 119,  35,  28, 124,  82,  12,  36], [  3, 138, 111,  60,  51,  27,   9, 100,  90, 144], [125,  23,  22,  90,  35,  85,  67, 134,  97,  61], [ 97, 148,  96,  61,  38,   5,  48,  25,  46, 143], [ 17, 136,  84,  90,  85,  85, 117,  98, 110,  65], [ 59, 137, 101,  23,   2, 133,  60,  37,   2, 145], [ 38,  95,  11,  88, 137,  24,  44, 109,  48,  91], [131,  13, 136, 138,  15,  89,  20,  21,   5, 143], [ 74,  54,  26,  91,  45, 143, 105,  45,  46,  80], [ 73,  15, 132,  29, 143,  56,  48, 133,  61,  82], [ 28, 147,  25,  41,  42, 106,  51, 102,  43, 128], [123, 143, 123,  84,  68, 149,  53,  78,  12, 115], [ 81,  91, 116,  12, 123, 128,  17, 116,  17,  71], [ 49, 131, 124, 140,  27, 124, 112,  89, 129,  12], [118, 115,  43, 143,  19,  92, 105,  75,  93,  84], [  4, 135,  84,  73, 121,  91, 122,  37,  54,  24], [139,  78,  48, 141, 138, 127,  14,  61,  55,   8], [ 56,  62, 114,  55,  37,  73, 132, 120, 123,  98], [ 16,  32, 105,  87,  88,  89,  63,  61, 104, 137], [132,  78, 115, 103,  16,  61,  74,  11,  17,  36], [119,  86,  18,  26,  92,  74,  90,  56, 101,  21], [114, 105,  81,  60, 138,  21,  27, 128,  39,  36], [ 59,  93,   7,  48,  51,   4, 127,  73,  42,  30], [ 32, 118, 141,  36,  40,  42, 103,  18,  54,  55], [118, 129,  61,  71,  22,  38,  37, 145,  96,  26], [ 46, 130,   6, 132, 124,  26, 112,  47, 105,  15], [134, 100,   7,  74, 146,  34,  18, 109, 134,  61], [ 27,  60, 137,   9,  11, 113,  73,  10, 106, 120], [ 22,  13, 129,  30, 122,  83,  49,  84, 107, 118], [ 92,  85,   1, 145,  54, 143, 113, 110, 135, 110], [111,  55,  59, 141, 143,  22,  24,  28, 114,  12], [ 79,  92,  65,  34,  88,  81,  49,  69,  55, 106], [ 56,  92, 147,  64, 132,  80, 145, 145,  87,  59], [ 85,  12,  41,  95,  99,  40,  59,  37, 125,  55], [ 27,  36, 133,   5,  76,  79, 125,  94,  64,  49], [ 86, 103,  87, 131,  86, 127,  78,  70, 143,  21], [133, 115, 126,  66,  19,  61,   1,  51, 113,  51], [121, 114, 109, 124,  79,  83, 100, 111,  14, 149], [  1, 131, 128,  23, 116,  80,  80,  71,  84,  36]])

# End of the code

You MUST upload the notebook you used to implement the functions to the mailbox enabled for this purpose so that these questions are qualified.

In [1]:
import pandas as pd
df = pd.DataFrame(columns=list("ABCDEFGHIJ"),data=[[ 33, 29, 101, 3, 69, 128, 65, 50, 52, 146],
                                                   [135, 74, 97, 45, 33, 58, 99, 92, 35, 119],
                                                   [ 45, 77, 119, 64, 22, 119, 42, 146, 96, 95],
                                                   [ 63, 37, 1, 47, 73, 35, 75, 51, 18, 82],
                                                   [ 90, 33, 58, 62, 92, 55, 40, 27, 42, 25],
                                                   [107, 37, 73, 130, 45, 52, 40, 124, 77, 65],
                                                   [137, 110, 130, 123, 97, 88, 101, 149, 81, 4],
                                                   [ 75, 76, 111, 118, 35, 36, 72, 87, 19, 32], [ 88, 31, 83, 23, 103, 35, 23, 43, 144, 8], [102, 6, 106, 144, 102, 80, 50, 139, 104, 66], [ 34, 62, 138, 139, 112, 8, 104, 122, 91, 115], [ 60, 61, 4, 73, 63, 16, 140, 104, 53, 77], [ 66, 128, 82, 130, 11, 90, 122, 145, 55, 98], [ 86, 142, 62, 20, 31, 15, 107, 136, 4, 117], [ 13, 43, 52, 49, 87, 137, 40, 145, 27, 140], [131, 77, 77, 133, 131, 118, 56, 122, 120, 57], [140, 115, 32, 140, 90, 121, 24, 133, 138, 118], [ 10, 138, 130, 113, 87, 63, 22, 25, 128, 92], [ 15, 37, 55, 74, 125, 42, 20, 58, 133, 109], [116, 86, 94, 18, 70, 39, 148, 75, 120, 127], [ 71, 66, 34, 86, 43, 143, 31, 66, 101, 136], [119, 121, 29, 52, 47, 87, 18, 23, 75, 36], [106, 142, 6, 17, 131, 81, 1, 120, 43, 34], [106, 11, 51, 114, 62, 104, 60, 45, 114, 4], [ 80, 110, 102, 14, 114, 123, 145, 51, 122, 118], [143, 124, 145, 19, 140, 67, 70, 88, 61, 95], [148, 124, 64, 76, 44, 75, 23, 33, 14, 52], [103, 102, 108, 30, 34, 144, 82, 126, 71, 117], [ 65, 91, 134, 86, 72, 21, 140, 50, 11, 29], [ 61, 75, 116, 103, 43, 24, 11, 46, 24, 64], [107, 111, 19, 2, 60, 98, 90, 78, 149, 113], [ 69, 18, 146, 98, 132, 58, 76, 45, 3, 31], [ 72, 4, 128, 52, 91, 85, 8, 120, 63, 34], [104, 119, 144, 102, 115, 28, 10, 103, 104, 51], [ 66, 36, 75, 9, 138, 110, 92, 119, 116, 76], [128, 144, 124, 43, 126, 103, 97, 7, 25, 126], [ 36, 3, 145, 107, 28, 146, 88, 54, 107, 10], [ 74, 89, 106, 127, 119, 90, 74, 149, 8, 5], [ 83, 18, 18, 84, 20, 60, 115, 106, 66, 128], [ 90, 18, 19, 117, 68, 33, 70, 41, 83, 42], [108, 109, 55, 15, 43, 7, 34, 65, 118, 144], [ 28, 123, 24, 148, 81, 142, 113, 112, 36, 138], [ 52, 108, 35, 5, 125, 82, 10, 27, 64, 67], [139, 149, 76, 35, 72, 83, 54, 72, 97, 123], [ 37, 22, 143, 105, 147, 61, 140, 27, 141, 117], [148, 126, 118, 32, 99, 139, 101, 136, 50, 86], [142, 131, 58, 105, 61, 128, 38, 142, 121, 11], [141, 127, 46, 141, 132, 66, 7, 113, 116, 105], [ 20, 18, 89, 60, 58, 37, 86, 67, 109, 117], [ 47, 45, 120, 136, 124, 51, 69, 49, 62, 115], [124, 138, 93, 28, 95, 82, 115, 97, 28, 81], [ 36, 108, 50, 17, 105, 125, 105, 65, 50, 42], [118, 53, 100, 129, 73, 132, 148, 61, 66, 54], [ 40, 120, 51, 143, 88, 128, 4, 93, 79, 97], [ 48, 97, 133, 124, 132, 98, 8, 36, 38, 71], [ 33, 108, 61, 33, 12, 132, 37, 102, 141, 27], [ 31, 69, 139, 3, 21, 40, 124, 47, 86, 143], [ 66, 38, 100, 9, 67, 45, 20, 62, 130, 65], [ 5, 31, 85, 16, 40, 132, 147, 92, 18, 123], [ 88, 51, 129, 68, 18, 81, 15, 118, 50, 92], [140, 49, 122, 134, 94, 58, 138, 71, 25, 96], [134, 93, 17, 119, 35, 28, 124, 82, 12, 36], [ 3, 138, 111, 60, 51, 27, 9, 100, 90, 144], [125, 23, 22, 90, 35, 85, 67, 134, 97, 61], [ 97, 148, 96, 61, 38, 5, 48, 25, 46, 143], [ 17, 136, 84, 90, 85, 85, 117, 98, 110, 65], [ 59, 137, 101, 23, 2, 133, 60, 37, 2, 145], [ 38, 95, 11, 88, 137, 24, 44, 109, 48, 91], [131, 13, 136, 138, 15, 89, 20, 21, 5, 143], [ 74, 54, 26, 91, 45, 143, 105, 45, 46, 80], [ 73, 15, 132, 29, 143, 56, 48, 133, 61, 82], [ 28, 147, 25, 41, 42, 106, 51, 102, 43, 128], [123, 143, 123, 84, 68, 149, 53, 78, 12, 115], [ 81, 91, 116, 12, 123, 128, 17, 116, 17, 71], [ 49, 131, 124, 140, 27, 124, 112, 89, 129, 12], [118, 115, 43, 143, 19, 92, 105, 75, 93, 84], [ 4, 135, 84, 73, 121, 91, 122, 37, 54, 24], [139, 78, 48, 141, 138, 127, 14, 61, 55, 8], [ 56, 62, 114, 55, 37, 73, 132, 120, 123, 98], [ 16, 32, 105, 87, 88, 89, 63, 61, 104, 137], [132, 78, 115, 103, 16, 61, 74, 11, 17, 36], [119, 86, 18, 26, 92, 74, 90, 56, 101, 21], [114, 105, 81, 60, 138, 21, 27, 128, 39, 36], [ 59, 93, 7, 48, 51, 4, 127, 73, 42, 30], [ 32, 118, 141, 36, 40, 42, 103, 18, 54, 55], [118, 129, 61, 71, 22, 38, 37, 145, 96, 26], [ 46, 130, 6, 132, 124, 26, 112, 47, 105, 15], [134, 100, 7, 74, 146, 34, 18, 109, 134, 61], [ 27, 60, 137, 9, 11, 113, 73, 10, 106, 120], [ 22, 13, 129, 30, 122, 83, 49, 84, 107, 118], [ 92, 85, 1, 145, 54, 143, 113, 110, 135, 110], [111, 55, 59, 141, 143, 22, 24, 28, 114, 12], [ 79, 92, 65, 34, 88, 81, 49, 69, 55, 106], [ 56, 92, 147, 64, 132, 80, 145, 145, 87, 59], [ 85, 12, 41, 95, 99, 40, 59, 37, 125, 55], [ 27, 36, 133, 5, 76, 79, 125, 94, 64, 49], [ 86, 103, 87, 131, 86, 127, 78, 70, 143, 21], [133, 115, 126, 66, 19, 61, 1, 51, 113, 51], [121, 114, 109, 124, 79, 83, 100, 111, 14, 149], [ 1, 131, 128, 23, 116, 80, 80, 71, 84, 36]])

## Question 8

In [12]:
#Implement the following code and select the correct answer:

def question8(df):
    """
    Write a function that returns a list with the medians of the odds columns (A, C, E, ...)
    """
    x=[]
    x.append(df['A'].median())
    x.append(df['C'].median())
    x.append(df['E'].median())
    x.append(df['G'].median())
    x.append(df['I'].median())
    return x
print("The answer to question 8 is {}".format(question8(df)))

The answer to question 8 is [79.5, 88.0, 74.5, 69.5, 73.0]

In [3]:
# Answer:

# a. [91.0, 73.0, 81.0, 76.5, 78.5]
# b. [79.5, 88.0, 74.5, 69.5, 73.0]
# c. [79.5, 91.0, 88.0, 73.0, 74.5]
# d. [79.27, 82.61, 76.95, 69.99, 74.04]

## Question 9

In [4]:
#Implement the following code and select the correct answer:

def question9(df):
    """
    Write a function that returns the number of different elements the column C has.
    """ 
    a = df.C.nunique()
    
    return a
    
print("The answer to question 9 is {}".format(question9(df)))

The answer to question 9 is 79

In [5]:
# Answer:

# a.79
# b. 72
# c. 81
# d. 75

## Question 10

In [19]:
#Implement the following code and select the correct answer:
def question10(words):
    """
    Write a function that returns the list of columns that have, at least, a 100.
    """  
    x = df.columns[(df==100).any(axis=0)]


    return list(x)

print("The answer to quiestion 10 is {}".format(question10(df)))

The answer to quiestion 10 is ['B', 'C', 'G', 'H']

In [7]:
# Answer:

# a. ['A', 'C', 'E', 'H']
# b. ['B', 'C', 'D', 'H']
# c. ['A', 'B', 'G', 'J']
# d. ['B', 'C', 'G', 'H']